apiVersion: v1
kind: Secret
metadata:
  name: obsidian-livesync
  labels:
    app: obsidian-livesync
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:cknAGRIqVMwO,iv:VtU40TDEYizlMDEKxagBBBGANOgfYYI1fS4t+kd2e58=,tag:hpzhxuu3p5HlR4oZFhelCw==,type:str]
  password: ENC[AES256_GCM,data:r1PKI/Aa3LLm0q3bT+ihjUo6fLmhUfi9,iv:8HNNx7WG/fLawwxkxJKOmf6LuyI/C4rZvkD3uI/gW/I=,tag:i6CRwvU2SDKOLrisrTrPIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaVNGWEh2ODdoRjdVZldO
        TUNRMGdueUgvU29HdC9CTVVlY3o0S2M2UjFFCjFRN1JwUld5dEErZ3RhNmRycHFn
        cExsWGNBSGE1cFlqbVFzMkMyTE1GdTgKLS0tIHJTejJKZ0Z4VzRBc0ZiczcydHpS
        SWN3REorenlHOTlDQW5KRXdDZ1pWKzAKx7eRd+KUW2bKrEPOk+/jIkcNUjf4clso
        q/aJaqht6nxn3lYa2zEsifC9UDsvc4KTXwTxWjE8CN61zpESd8zeTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T16:06:05Z"
  mac: ENC[AES256_GCM,data:lu1fAKlxko4s+L9y2AUE/x779U2VTi2vJ+O/lD5gZ3QgtTR/zvIJsXuHV4EoHNWctIUtV9faTBsMr3lmycjlP5q7HaoP4l6tKQ14zhtldBImCe4q+b2ko0u4an1AEfhBBGmPBVrXwkK51CaM/rxQyVt+HDHzHDREFtc4wvxFLLY=,iv:BZZ8NP/lmj+D1XruJBUK7yYXJ4dH18C/z0/Dtl+8Nic=,tag:hf8O9ZRwtP+LtrG362mFZw==,type:str]
  version: 3.13.2
