ipam:
  mode: kubernetes
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
  privileged: true
  allowPrivilegeEscalation: true
  runAsNonRoot: false
  seccompProfile:
    type: Unconfined
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
l2announcements:
  enabled: true
externalIPs:
  enabled: true
k8sClientRateLimit:
  qps: 50
  burst: 100
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    type: LoadBalancer
    hostPort:
      # HostPorts can short-circuit the datapath and make debugging harder.
      # Rely on the LoadBalancer service VIP instead.
      enabled: false
      http: 80
      https: 443
  securityContext:
    privileged: true
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    seccompProfile:
      type: Unconfined
  enforceHttps: false
podSecurityPolicy:
  enabled: true
  privileged: true
  allowPrivilegeEscalation: true
  hostNetwork: true
  hostPID: true
  hostIPC: true
  volumes:
    - configMap
    - secret
    - emptyDir
    - hostPath
    - persistentVolumeClaim
  allowedCapabilities:
    - '*'
  allowedHostPaths:
    - pathPrefix: "/sys/fs/bpf"
    - pathPrefix: "/var/run/cilium"
    - pathPrefix: "/var/lib/cilium"
    - pathPrefix: "/proc"
    - pathPrefix: "/lib/modules"
routingMode: tunnel
enableIPv4Masquerade: true
