apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./sonarr
  - ./radarr
  - ./bazarr
  - ./prowlarr
  - ./seerr
  - ./transmission
  - ./flaresolverr
  - ./profilarr
