creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1rf27l7lxj2dd78ah4nqv63ezqm5l2zlwzlqjx4y05pnvfy5tsu6s6ye0e6"
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1rf27l7lxj2dd78ah4nqv63ezqm5l2zlwzlqjx4y05pnvfy5tsu6s6ye0e6"
stores:
  yaml:
    indent: 2
