creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1gzp39gyv25y689qnwl74tuj5qls2g4zgu3rllf83syu9eveje37s3gdlq2"
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1gzp39gyv25y689qnwl74tuj5qls2g4zgu3rllf83syu9eveje37s3gdlq2"
stores:
  yaml:
    indent: 2
