creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm"
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm"
stores:
  yaml:
    indent: 2
