# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
includes:
  talos: .taskfiles/talos.yaml
  bootstrap: .taskfiles/bootstrap.yaml
vars:
  TALOS_DIR: "{{ .ROOT_DIR }}/talos"
  TALOS_CONFIG: "{{ .TALOS_DIR }}/clusterconfig/talosconfig"
  KUBE_CONFIG: "{{ .TALOS_DIR }}/clusterconfig/kubeconfig"
  AGE_DIR: ~/.config/sops/age
  AGE_FILE: "{{.AGE_DIR}}/keys.txt"
  SOPS_CONFIG_FILE: "{{.ROOT_DIR}}/.sops.yaml"
tasks:
  default:
    silent: true
    cmds:
      - task -l
