apiVersion: v1
kind: Secret
metadata:
  name: explo-credentials
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:VnjfKK44kgmdvCCZkg44i1WT3cg=,iv:ivh0N79yOFzeikPxWzm7y0nhvVMyhTpIxKoHinsDLi4=,tag:/AqCy9vOvJLHgyK8KaQTww==,type:comment]
  UI_USERNAME: ENC[AES256_GCM,data:ERfgMPM=,iv:aPbIXOSIWie9EUvdlPy41bj9HkrSUZYHZmjuUfl3UY8=,tag:1tnrVRAVQdr2GCKMFdXn1A==,type:str]
  UI_PASSWORD: ENC[AES256_GCM,data:S7uZ8CK2NPUVZQYhlZSi/TJ/af8=,iv:KktStZPXp3MFFWnlr+wh9G3snm8m7pKpiSOFHwDTVkM=,tag:wMlS3KgJEEqZQHxF/WAmeg==,type:str]
  #ENC[AES256_GCM,data:w0qTFYm0Lci3Al+mVe0VW0F7XggB+FR/PaUF/o7nORvNS21GVsSvsWFHwg5MmXnMQEYFq+7BLX7g4dIhO0juUij41XUU4hUQnt5AdySPTexvmDU+uO4=,iv:Z+hoIg2TpS5qUHxEXckkcpnR0rxLRZ/016rI5ZcTqFk=,tag:XKuJ5+C/4whJ9k9JJKb47Q==,type:comment]
  LISTENBRAINZ_USER: ENC[AES256_GCM,data:mjVZIW97sKb3bc8=,iv:7fSlhpKbXDfLrI56aUUK3vRgJjYWKd0YKYMsVikjSxw=,tag:t8JJnWONOIhWp2ED4lWMbA==,type:str]
  LISTENBRAINZ_USER_TOKEN: ENC[AES256_GCM,data:VTdV7Ylocfq97LFFWuKx6ii2meOKXw6hzE0S1IiDsoRsOZPb,iv:6p8kLO5lfAKkd3a+gjrSjS5vYcGESznMOHHOiQz8YGM=,tag:wOXCq8icFvJ8edKK6fM7jA==,type:str]
  #ENC[AES256_GCM,data:CqkDWdDKS3/RpJ57wN8bvKnPfz/xht+PL752PkxqUu97VCyfoNBj0nMs2VNKPFBDkM1x3a6AnagDgSvKyY0=,iv:8FiJZMRjXESc3C1ef/elLX8kiLu8qN079ufgKlinXV0=,tag:DiJABAbu4heJ8uxtfhNQGw==,type:comment]
  SYSTEM_USERNAME: ENC[AES256_GCM,data:YKK36g0=,iv:RWHUVVdS0DflUf4dnMtJg7GMoTJcemdgvsdhWYHXPJM=,tag:8DzTme/HMrO7W30AR6xf4w==,type:str]
  SYSTEM_PASSWORD: ENC[AES256_GCM,data:8qHLFO42hVJkuV73lLn2a2v3expWeI15,iv:/UWv4XdBgdqk/aJ8k5CCqKCYw3+KwT+fHZPvYFh3yY0=,tag:YA/kaETzGUNYrX+hV5+Dfg==,type:str]
  #ENC[AES256_GCM,data:xDud+hi/q23dEUr4YqV4DK0pA8ecGzUP0xovxSbKN8safvWD3rCBm+NL6NoLMymCNw==,iv:dvAJ55UzRXy+gK6db2sdcEvOHY243UY2dfQQZlNOkqE=,tag:sqPleM9z/WtCRCbso8r64Q==,type:comment]
  LIDARR_API_KEY: ENC[AES256_GCM,data:o+s9ycthxPxOmgOg852fIL8hmKxT3QfcJy9FGy7IDt8=,iv:z6z+eW9zBR8FFpf0yWYTC1cjBM7pjcJqT8AYhqxOFEE=,tag:2y7U+VKTLFe9w5nT2N5Gdw==,type:str]
  SLSKD_API_KEY: ENC[AES256_GCM,data:CCsDTfsbt0DCReox3Cp+PnGj6wRwbDShnq71pbK/NvgiFtFUSvo+4/CwT94CKP1CYUodca/x9NIiBdlKll0DvQ==,iv:/0RcFLr4D/SD1J78I6KiF6wKPLfQsyuQ7qWtD/5ZZcU=,tag:I2P4NU6lj/DkXB1k8BngRg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSDJUWFptY1JkNFdsRDVL
        ZzNyQXpHWngzNngrY2k2RXJlK01XQ0NlU1VRCmRjR3d2K3ZON2thT05iOWVjYzVy
        VGpJamNXM3p1UVQ2RHAyQ2oyRHc4YjAKLS0tIGx4YU8xczUwWTZsa2M4S2RtbjJV
        akRaa3I0NFNNUTJXZHFROGV5UVJCdncKkAP1CDCl5LJpgFHCo/Jb3UQYmcIyfUVv
        H811AMNtUQF9LFCWQqCAGvOT7RMsWNVgt4QcAyTg9LhmpLLGg9Av3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T17:51:12Z"
  mac: ENC[AES256_GCM,data:C/e5arYVdtM129QcAPFIaInYRJRThhmm6P/4/OH+TYMWOE/rxMOfJFAnFE2Wnhd8oI8xGt14/yFGx+vM5TeeGz1wNpkEyyPimU0WfY3BcPDCxNuOLOy9PH14JZVTR1jD+F8sjqFiwAbuRpzOjPKqE0hayJJkwKFksALk3n0WvvI=,iv:LqtP0Ne1EKRe2LV7ePGMcYqA1iNo6eLQYHw8IawYiL8=,tag:BhMiHqHC0rYmiUqUQJj2XQ==,type:str]
  version: 3.13.3
