apiVersion: v1
kind: Secret
metadata:
  name: soularr-credentials
  namespace: media
stringData:
  LIDARR_API_KEY: ENC[AES256_GCM,data:Ex8LghU8+/vIrSYHCxUifwOHGABo4AgyqFIkmyVHLb4=,iv:nkVBBvovGSFQ2WkXUgRtyptzp0Z+TGrD1xTw701bwMc=,tag:papDXmhTpTt78+b1oLPfsg==,type:str]
  SLSKD_API_KEY: ENC[AES256_GCM,data:c912p8fDElE24neFwicqY6hWviVVIWk+xBsXsbZuXf9CUGa7a7pgm4+0VVX/J9478XswUAWHzmWD4fMeA7v8TA==,iv:89NgIIHX7JsPgT28wlNQxJuV+Zzh4mf8IVN1W9AUffU=,tag:pnqNBZGRzpxOkfodDziQdw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VG1sc2V1TDZzN3ZCWWo2
        ZXBaME5Pdld0YnphSGpGSjVyNFJrbTk4SkdzCmxscHZDUUU0UzU1MFhYRTlOY25z
        UDV1Qk9ESlVvM2xVR2MvRTIzQWR2TlUKLS0tIDVWR0tNOGNKTUo4ODJGbm43RDNX
        N2hOU2txZi9BNHJFRnplQXNPMzhhYWcKsghdx1kdmrjLk6BtQFQSK/qeers+wiZN
        DUNx2BOxFKlr0YWyhZogp/nweGL1QBBYffFahUT/KkHV8jQIvKIvug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T08:55:53Z"
  mac: ENC[AES256_GCM,data:mKnLHK+q4HI04+XpMxiCRs6cjjd77FK0AlMw+0kouS91tKa6Y+q4m2FWcf9ytEwepyTUSHcvseI00VhmNNyjaoj+HE+WlDZkyocVzU20PeFRoHQ+bdSF5hsV8alZJEh35gsHlz0+xbHUnriTNomHmnlgGVsbFxFsGPxYhfi4GJo=,iv:IW4BkjImu2C7UK6eOjsXz+mT6lh8prwj7sYMLlUE4io=,tag:EnBHXK4a23OCHQU7wP76gQ==,type:str]
  version: 3.13.3
