controllers:
  main:
    replicas: 1
    containers:
      main:
        image:
          repository: ghcr.io/linuxserver/bazarr
          tag: 1.5.6
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 100
          TZ: UTC

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 6767

ingress:
  main:
    className: cilium
    annotations:
      ingress.cilium.io/loadbalancer-mode: shared
    hosts:
      - host: bazarr.lab254.lab.lan
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 1Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        main:
          - path: /config
