---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  labels:
    app: minecraft
data:
  EULA: "TRUE"
  TYPE: FABRIC
  FABRIC_LAUNCHER_VERSION: "1.1.1"
  FABRIC_LOADER_VERSION: "0.19.3"
  VERSION: "26.1.2"
  MEMORY: 4G
  TZ: Europe/Brussels
  USE_AIKAR_FLAGS: "true"
  DIFFICULTY: normal
  MODE: survival
  MOTD: Minecraft Server
  MAX_PLAYERS: "10"
  VIEW_DISTANCE: "32"

  # RCON is enabled by default; required for graceful shutdown.
  RCON_PASSWORD_FILE: /run/secrets/rcon/password
  SERVER_HOST: localhost
  SERVER_PORT: "25565"
  STOP_DURATION: "60"
  # Mods
  MODRINTH_PROJECTS: |
    fabric-api
    lithium
    scalablelux
    ferrite-core
    c2me-fabric
    zfastnoise
  # Whitelist
  ENABLE_WHITELIST: "true"
  WHITELIST: "jumperlow"
