apiVersion: v1
kind: Secret
metadata:
  name: minecraft-rcon
  labels:
    app: minecraft
type: Opaque
stringData:
  #ENC[AES256_GCM,data:/p1hLUNutoPLqRX6PcVqOo9EjViPV00UTvYtX9E5l+ycz49vcSZ++ICQ7RbDK+DsupIHge+3IUfr814uoeFE9QfmPK7DAxsazcCRmb2MK2AIBQ==,iv:xENEmFpp6/TU4D13eGwXrS1AILDewfo/LmopRwXTc7g=,tag:X6p5aDtJ6kIy+cSYs5k1ng==,type:comment]
  password: ENC[AES256_GCM,data:usTKgtodNTI=,iv:AtL61RfvSXWe6E390rGdu+Ie88sBKYFy5/k1J8g5gmk=,tag:Q8GWCs/hQNYnqedvaVY/Tg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcStKR0lQMHltek82Rm9V
        R1JKeGwzZ2MyZy93alB0ZGszR0JwdmhQdWpNClJBL0pUM1FreVNUVFBQcHBhem16
        bm1TcmlScW9tYi9hR0dacVNxOTl5NkUKLS0tIHZ5cFdLUFZZWEE0UEdPTzMwclNw
        UFBYcWpwa3R6MENFTGRweENrN1NCNWsKimblZHg6bDtVD+lbufODMkXZOx2KEzJu
        EuK8esDQeaJzzNXoPVBGg2pdSGU8nC5aq0w9/7q6PkLSuqB6/do8EA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T17:49:50Z"
  mac: ENC[AES256_GCM,data:+ngqQt42xYtM1C8N9XjTCrJfHXtMjd4B2QW5J7YA0xqzQvL34vrmSKoC6Rjl72E9E79d//Mgsd0JepqkGKhP0taAOl82aYYruY0UMqn6n9soE841S1fJNweVcsrQZ8V+m9GmXmwhcTis1HLMUYLvs4EB5vGR78eSEiEYsW8QR8Y=,iv:xu9Lq7Rd7mFb2ZZ6GCgBUgC4OaqYEloIoVmNc7cJcAY=,tag:sJGQamxtLdUkVAjsg0h9IQ==,type:str]
  version: 3.13.1
