controllers:
  main:
    replicas: 1
    containers:
      main:
        image:
          repository: jlesage/musicbrainz-picard
          tag: v26.09.1
          pullPolicy: IfNotPresent
        env:
          TZ: Europe/Brussels
          USER_ID: 1000
          GROUP_ID: 100
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 2Gi

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 5800

ingress:
  main:
    className: cilium
    annotations:
      ingress.cilium.io/loadbalancer-mode: shared
    hosts:
      - host: picard.lab254.lab.lan
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 2Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        main:
          - path: /config
  music:
    enabled: true
    type: nfs
    server: 172.16.2.23
    path: /Plex
    advancedMounts:
      main:
        main:
          - path: /storage
