---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-storage
  namespace: default
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
  namespace: default
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.2.23
    path: /Immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: ""
  volumeName: immich-nfs