controllers:
  main:
    replicas: 1
    containers:
      main:
        image:
          repository: ghcr.io/linuxserver/prowlarr
          tag: 2.3.5
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 100
          TZ: UTC

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 9696

ingress:
  main:
    className: cilium
    annotations:
      ingress.cilium.io/loadbalancer-mode: shared
    hosts:
      - host: prowlarr.lab254.lab.lan
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 2Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        main:
          - path: /config
