apiVersion: v1
kind: Secret
metadata:
  name: slskd-credentials
  namespace: media
stringData:
  SLSKD_API_KEY: ENC[AES256_GCM,data:tI7fE09mfzzRlEJ8YKT3JkKWJxj06LWbNAYEcFJ3AwetlJdcHdLK4PzbLR25j/B1L4tRxqprr3OATjquH3LN+w==,iv:103bKD/do6R3V1GLsnDIAXja7jl1a4/Hqh6Myta4vYA=,tag:hdOS04WMTDDvO6Nnw3zcPQ==,type:str]
  SLSKD_USERNAME: ENC[AES256_GCM,data:iQEw9JE=,iv:s05ExwQIyF4f6RGjd4xORm91Z0chPMPVFQg6l/AhJZw=,tag:P6wm0EcSCMxsCgEMEOFiew==,type:str]
  SLSKD_PASSWORD: ENC[AES256_GCM,data:OFfbP+QBtvdecOqtKpRu0Nob1cdK11nn,iv:DErZMqEWqfF/AIIVWj3lC6iHbANEtGGel3KNYmN9DMc=,tag:bjWskrYg4sy4fBOdInW5vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cjE3ZkwrVEtpUDMrdnB1
        Nkw2OTNubGpFZlNGdVBLT2NtSEJHZWRuMFdVCjROcXE3eDYxWFpjQXo2RlVzRnZj
        VE9xb2FYUEEyR0hicmJQY0h0dDRpMmcKLS0tIHdWSldvaXhJTmFKcUY2Tlcrc1FS
        blMzVnMxK2VQTzN1b01aejlVczNyU2cK3JTVGuH/LDMyGZQLS6L3/+6rWo8jurYN
        S8YjTsSlrsc2wA0sFuclcXd0BroK8UajxRM+Urza5Y+n2aiU2ppAWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T08:55:51Z"
  mac: ENC[AES256_GCM,data:sVHmiy3kv4SZKBODOIDULX7kOroqBMUq99tC/6s7JfIUWHBv3GhU2c0bPwXzFMr4BrRb38kn7zh5lPcyF8em/4EqB+OXCcB+CiFYmFAwrQs3gpAoTDQ2ClTCJNbEbGFaF4NDBQqiNr5SM+t7oVFdeliBDg/s4mPoRt6AMROW2VU=,iv:MAhm74TycTZyw+QKuBrN/nl4xRurV/cf994nIeP+dHk=,tag:WmmZUrAZSet1CDju6xht2w==,type:str]
  version: 3.13.3
