apiVersion: v1
kind: Secret
metadata:
  name: slskd-credentials
  namespace: media
stringData:
  SLSKD_API_KEY: ENC[AES256_GCM,data:JdFgbXP8jdP0T8fYtPKOmFDNOdBasW8ae0bcOwXfyiNr5OiYmXvwPKVQtAbmkZoJLvOmwojP7dge4fmrKxUI5g==,iv:A62JyoJvcU9o5k3mAGjV7lyD9yibZ8VxB9Xs5xHfyZ4=,tag:M1XRINOt8nfk0q36EqOw2Q==,type:str]
  SLSKD_USERNAME: ENC[AES256_GCM,data:eKXJGHQ=,iv:NFdgKtHDqfx/nWt5a1Pc4x0D8CzEVssRcbOuwdCawWg=,tag:floOXnbtSiKJWgGX9tcdHw==,type:str]
  SLSKD_PASSWORD: ENC[AES256_GCM,data:Wj1VbKOvVRQop5aSNEgO02B9qD41w3/J,iv:VbCKBbC0epU1jYnFI+jDoGel7Mm7UyQcgrsP5m5EYEE=,tag:0ZlMDeaxn/LGWG2m6tWR3w==,type:str]
  SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:T8n+nCt+SaG+k7k=,iv:KkM0seM9xJzR6Riur/WGy2Qfu36Luvv6lrWdN/YVy3s=,tag:rPwNnOgN3QBx2GEemlf2bA==,type:str]
  SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:4aziimQhdpZgQjFSNiBQK9n3urLLbRuX,iv:UEL2zaOoYr0rzci/Z/9N+k3tPAaZgvOLyDAjTXFTZ44=,tag:UgQMJH45s9DfHebTwp93Xw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyKzJPV1YvMmFKTkJqVk9J
        VXk2QUxjNnJZY3pKSFF5SVJEZ0V3bmxLbjIwClVMYWhUVDF1Sk5xRm9ZRCtpU2pH
        Vi9xZHhCaWZKQUVvWWpYWmYvL1psdW8KLS0tIEY4U1ByT1JZSldCbC9TL0FSaUEv
        eXNTcWhoVk4rV3BYM0ZkZitIeW5NYjgK8P+XTYb/3QWDX88SPtM/EmODFBVUyqo8
        7qwQ+ZdMK3s5NEBO4ccHWuuyD/W7+Nmh24oGAs//1K61zf0emQTEyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T10:20:44Z"
  mac: ENC[AES256_GCM,data:ud/EZ0/MWZUft/3JQH+CS+GPqDAf5/2U1w2kRMc35JDrw1bChjLhSS3DzVPToDACkQ1kvn76nFKWT6Y9RVdCzS9EXnW84htTBMVFRsCyzxKsnKhdIVXWzuFqI9usLOPnDpnho/sC6T7wXYTYqqwv6llaPRo480DBT/S2GLkHVHo=,iv:1wNpw4mZJSstJAXytxarE/QtvQZVR/rH96ru97fA5Do=,tag:46j7h4NRhMBmxHfV5ypUgw==,type:str]
  version: 3.13.3
