apiVersion: v1
kind: Secret
metadata:
  name: slskd-credentials
  namespace: media
stringData:
  SLSKD_API_KEY: ENC[AES256_GCM,data:fIfzRJ+PC0AjTQWdmhV+ycj722lYo1CWMhWN5n8+3ojDIOM5Yj2zSpeqOK1HlFX2c9FSPP+w62UvbYRAwV4nfQ==,iv:eAmszpBxhOnwV+vrvbtcNYZidS1ra1LWzbiqRrX6mJw=,tag:sjqq+mMISnP6XygraJgDxw==,type:str]
  SLSKD_USERNAME: ENC[AES256_GCM,data:pVb2AG4=,iv:/cRwXSu0YkaMRPXoKONGejo4xzR6m2qxfmMR4R/ByAY=,tag:1L8ab1AgiYN7ycHv+WjKOg==,type:str]
  SLSKD_PASSWORD: ENC[AES256_GCM,data:m/zE2F57oEboSuToJ/Q3q14WeaR9idFY,iv:jmlk2O9ltMRg9npabWVVewTRPT8Mtzx8zgdyttIoxd4=,tag:YgV3fMpwlSvZ7UQ6gkOxJA==,type:str]
  SLSKD_SOULSEEK_USERNAME: ENC[AES256_GCM,data:f+aCDgxcqGQDwaU=,iv:0LtVz0GiL40HAybBBPPNeXLH8QJvA+psyM3rbCksNY4=,tag:n2r3u/6CeWZT659Jp39SYg==,type:str]
  SLSKD_SOULSEEK_PASSWORD: ENC[AES256_GCM,data:2pfBGBvdMTYJSYRhM1N3wKQU6KPR97il,iv:MtHX/Nn5tc+1GOOqh8XM5dz9jTcfTJhNPUZRmcJg4Yc=,tag:52FwhAyllrKcg9IRukIdpw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQWpkMGQzVUhoUXYwa3Vi
        dDVUNU5ic1BxWUJJclNDN2ZJYlBweUxNS0NBCkRwOFo5MU5oRmlkbDBwaXMzM2NZ
        ZStGZVI4UEZaNXRWTzhnRnJEL2R4N1EKLS0tIHd1dkJ2VEllYWFUcDFPdzZWWE5m
        d2RsRDNpalQ2ZU1pNDY0VmFnTkhSNlUK5PvP1St9q5V88Br2c6u/QGGmIEnO4T1A
        C4MqxVdZlz1fQ2IoqN/0pZxWiUd/dJauqgZPI5vderrM7BemSMPuwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T10:11:56Z"
  mac: ENC[AES256_GCM,data:iobuN2mZbtJtwl2qXPCce840r/w9AC40MLLgo6X6xexThd8Y21FF5t3LNlE30JGNg48SDG/1c6l52tA8MwW9SaeEPSas4fFW+v5SvZgb1xuaVSgt572FSDurodLrDvBmiXrI2B5WbIDh1j09m8JbIogw1ZuJg1PO3zspv2FKqpA=,iv:4iZ85WofaizSgWYgJDXNTHZ56BuCrn4KSYy11504W0E=,tag:5RSJIHaOusWqxJ13OfWe5w==,type:str]
  version: 3.13.3
