apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SOME_SECRET: ENC[AES256_GCM,data:+yvRqv0skCL/Cw==,iv:8tHRcX4pf0+EwxUYvSfP6SH5v1GpmOiBhQVIKTjE5UY=,tag:nn/mN+UvKtm530Pfo/7VAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU0xEMlVwVXFWdUo5ekwx
        RHJXLzRIMEtaUjBxdS9USXQ0cG5HRy9QeGxrClB2RE9tSHRPYkRUOWo0RllHOE0y
        SmUyQlcxQWlYQmc2OWhPY1B0R05zeDgKLS0tIDYrV3l2SHVPeWZ4THJ1dmtwR3ht
        cnB4VEZWNGsyM2swODRzUUMxc2JvQVkKNdSkqsAJHQ1w8zX6nK+Z0L7YIz9/gnLl
        Z5s2lJtGhBadQqdA7+A24LzFU7qYpX/veZ6+ryrGkN9MP98S4LJOhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T12:21:08Z"
  mac: ENC[AES256_GCM,data:AGvZIfezXzECSloTVDmitBNA/URUx8+irO+Ru/sCRTsoYEmih/SKxFC2P9S+P2DxE9OFpJY6wkRs9+XsZnDOhj1zkuzkcSkRf6Yp08wNuaR766poQmJi3pEQu9yNOIoCVhV2uSSQzHpBkkGqOBmAia4MSbNTDFVRSOaUlWev+C4=,iv:YBZM2Ren070Ua5lVQURtcUTsIMrvsLxEFPRRFWv4XbU=,tag:O7SuGkHEZk3u1sECgv44SA==,type:str]
  version: 3.13.0
