apiVersion: v1
kind: Secret
metadata:
  name: lidify-credentials
  namespace: media
type: Opaque
stringData:
  last_fm_api_key: ENC[AES256_GCM,data:RZE283HEusjgwDUZoAbz/OjBX995MHpgbeA7xw4e9x8=,iv:jVSC8/AaFmu55jFza2ALQISm3C0IhHZmfKTPUhMN/EI=,tag:i1K8CMI4i6M9r+HIsXQY0w==,type:str]
  last_fm_api_secret: ENC[AES256_GCM,data:6BhdZxM1py4yLOQ/IT0iE50qKKw9ES/la7JMj39k4Mo=,iv:zLJNF1YJMdDq1IlvVEGaKDffUXZb7tI5J/tC3ULoMMw=,tag:k3GZBbso/WPs+VeRhEzxgw==,type:str]
  lidarr_api_key: ENC[AES256_GCM,data:uQ6J/9DFin69vc/fN9ywQJ+qO10SecgCW4YBASQps/M=,iv:siWnf7iD1I7Gr5mWXHrmuhgR7zLOX7TexDcxFy6lDqM=,tag:nDP946lTX/ckKq9u+Nx4cQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOW1Oejk0V1pGbUY5NVlY
        bEQva29VcUY5SzRCNTZVREtvMHAyU2tmbmpzClY0bm9oeE5rYzk1N2p5ZlF2YzZU
        cGFxZlNvNkZrRDRUb1FINlY0a1dLZWMKLS0tIFFYSUJ4RHd5ZGhHQ1gvWkNYL01C
        a1JXK3ZwanZhb1k4TTRlSFNSNGo1L0EKVLKJ/LrcrPZGgyHrt50YZclzYKEj3Ahg
        m4Xvk5p0/vyAUFNTZ63SH2PF9APIrLlxkeS8KVWOu8dE+N1ciWRZuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T16:43:12Z"
  mac: ENC[AES256_GCM,data:eLOmBKB8EzSPzcYKKKvuS+A7cSkQCpaH0Dt2XdTEMkNQ5nuOkjeUb/rvHfHRIhgQAyLqVolOXdqkv0EkY+aQ7I3Hcgc8YlUApxwhyIfXT88fcAPVXxRdyLzIKRGh5fYiygOd1FDgXZBzhDktgRVAjoZT5PeRuDTX7VM0hKRv7UE=,iv:bZ/EIjoVZprRc1Z6ck7hrrPi4d6lDGIloDzSSWR1GvM=,tag:i88WM8YRENKKU6Qd/YASoA==,type:str]
  version: 3.13.3
