controllers:
  main:
    replicas: 1
    containers:
      main:
        image:
          repository: ghcr.io/linuxserver/sonarr
          tag: 4.0.17
          pullPolicy: IfNotPresent
        env:
          PUID: 1000
          PGID: 100
          TZ: UTC

service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 8989

ingress:
  main:
    className: cilium
    annotations:
      ingress.cilium.io/loadbalancer-mode: shared
    hosts:
      - host: sonarr.lab254.lab.lan
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 5Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        main:
          - path: /config
  data:
    enabled: true
    type: nfs
    server: 172.16.2.23
    path: /Plex
    advancedMounts:
      main:
        main:
          - path: /data
