service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: cilium
  annotations:
    kubernetes.io/ingress.class: cilium
    ingress.cilium.io/loadbalancer-mode: shared
  hosts:
    - host: headlamp.k8s.lab.lan
      paths:
        - path: /
          type: Prefix
