apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  namespace: default
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:+7hLGYdIhDIEKMcsqc1ceHAvBawvaPL2iVLpy+Q0tZloeIiF,iv:NENgII2oGGiMWwlvcr/6arS+W+k6HMXPX/DrBnVZ0yY=,tag:fUzPcrPlp63dB1UzEEq8rw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/IQ8wes+D40DQe7hjypRub5XqGZOduZJ2SzLRCaYDOU=,iv:sliVyj7ZUyk/VWUwg3lkqYeaXsQFkpNyVItfP9lqY5w=,tag:efD5bUAPCMNgLlPtvotwvg==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:MHK0QvLdby4tS0VhQ5KTNS5BY1DrQYKYJQlq,iv:VjSOwh6bHgIQ1EuE79dKREQBYeIDEC0zEdYHw0w09QM=,tag:XhNEfBvTov48iz+5cIODlA==,type:str]
  #ENC[AES256_GCM,data:z143Q+0WSr/KITUaILqUzZ1rEdiD7XwYmQNmIVLjsLfBRpng2MwyzI9b1xe2rIqaxqD+GtyeVkgij7CJUg==,iv:bUCWEHS55WenuRlkcKNn+JEaysq2ImmggO57h377qEk=,tag:JvtWxKhn2wdsyNZZ9ImIPA==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T0x6T1NiQjZPZDlXWDJl
        bHVTTGJybUsxZlBkODhlWUMrc1loN0xPK1h3Clo0QUp1R2ZBaVRQWGNTV2tMMSs3
        RndDVWR4eE9tNyt0YU9PbGdydnArcnMKLS0tIEhmZXY0bmpmeUZ5U3IvaGN3anY1
        bHNQRi9SekxnOFFNa2ZyZ1lQcm1tL0EKTdnaIwg8RDdbMOmP/TOyKbfpVEGGirHH
        UA2wy1TI/5L+orHXwiJjVUM56dL0XvyaCSTqzLQ79u6nf0nF3Y5zbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T14:48:32Z"
  mac: ENC[AES256_GCM,data:lqZDdUllXydos3d7RkswB/OUqwU0mopYtTpOBTw53VepSXUcHUeNEkb0p1noQbzv8uv1aReEN5kFIZO0W3zTcN5qTuPr6bpYE2XPkXT3ns/3zp5C5OUYIfQqD9vD9y5b/vt42+oFFOjFY2HrRs6rxt6qpr2w5xRUoHsJhWtkzF4=,iv:6dpYDH8H+2D6oIKpc7tXMX9vA6sC1Wsjc3vs5/eJjl0=,tag:95JKPKcQJYjUtGIBZ0QzXQ==,type:str]
  version: 3.13.0
