apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  namespace: default
stringData:
  clientID: ENC[AES256_GCM,data:Rf5KA6SVHl0HxQqYk+r6LQHZSy6vODR5pf2KBRoE2C2oczLy,iv:qexKlM5XmHZuz2JZEb/FOmIeKZh9tlzk7I3Ov5bBm2o=,tag:JnFTK9qZ8kZS2tO7LtgLNw==,type:str]
  clientSecret: ENC[AES256_GCM,data:GNozo4/HqcaqfJ1nbSvrCaRGCrwMWgDbk+gvZsZCrKs=,iv:31WKFMM6nhMBcEFyCT3Os+ObSJzwZz+XKHLohgb/ViE=,tag:KjWthaSmn6ckhWq0PTCUlQ==,type:str]
  issuerURL: ENC[AES256_GCM,data:cXD75CUQV9KB2dDIuOIdVQN6touHmDrXUcwI,iv:uoD3D3aH2W9DoHlV9LE1craqN2STh6lbB2CWY7Z3+P4=,tag:nxieYUaWQu/7qfsIQoMKug==,type:str]
  meUserInfoURL: ENC[AES256_GCM,data:0YCFMarKmf+qAxPu/+ZpMjdzVbQIlaMsUV2GktdIhgUWgqRlLSomTrLOtT0W,iv:xVdtqBjRtHvgoEsHeWjzmQ5tDetjHX5dh6upZH2gusw=,tag:9/7a1clVJ9F1YYz/4eGKrQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN3djMnRMRi81TE4zbCsv
        M2lFbGp2UFI5YUJqdnhIaXRldjBRWm9Rd3lzCmpBNklWSmhTc3dtNm1qWFJCZDN3
        cnVIWGExQkViYUFWWmhoVnBUQXpWM3cKLS0tIDQ4L3dBNmpBazdGUUx3cVRIUzVN
        UHdhSmpTb29QelZYeWNWMGIwMzk0TTgKGg+IPYQMhgmWMbqbBTYS891rGuOgR4Jy
        0Wfmm63hfpPpZF0u2BFo7s01N3F5E9SjqC447at3qf6aJV06XHHlvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T14:42:32Z"
  mac: ENC[AES256_GCM,data:/Ifrj10znZurEbkJ15O1C5DcvPM2MTqjxPNYNPB0ljAHJn4dHrfbospIlxXW7dwKFN7xCqJ2MXCcBHMmkswwwauWxN/KdbTYstkLp9x0Os3Iuz+t5FEls8DxqfWDx7903TdINoagZvzpToChtpz7LXPGBa6J2e/dBxO9mk7FChU=,iv:HFV3eLRBnr2bzZm2BR6MUzgHS3QlI0FtlRzT/RIxR+A=,tag:B+7MlrfgtkSS4RcB1ah5dw==,type:str]
  version: 3.13.0
