apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  namespace: default
stringData:
  clientID: ENC[AES256_GCM,data:h7Lv+A6e8kTCOvHbqjlF1DgQt1XqPZ1Mn8Cj7dE1l4yTzAnh,iv:CTlisoRB1hmT3P5jPRubz4LN9WmELZT/7Vtq3h0MoeQ=,tag:mJdA3vbHL5SKGK8a2EGG/A==,type:str]
  clientSecret: ENC[AES256_GCM,data:hYKf9MYrZShbG05AnklLtYWpcvUAj8gB19AqC5FSDQw=,iv:RFDUXtIqz1qlHKom4wu7HpdD4EtVW0dRg1CbQIAbR1I=,tag:ikW98q0+7hIUdbZHR5nabA==,type:str]
  issuerURL: ENC[AES256_GCM,data:x5Dg2rYChflyYnhp56nYsHNqnYTloGh6U8tT,iv:DhrIIRRGJV8A2fXcaLdUcVythxxc20+1OjU/p10RoTs=,tag:nkcwJwOKjZ+w/HO1IvgB4g==,type:str]
  meUserInfoURL: ENC[AES256_GCM,data:D/39mhHtziraLfz9M1vGNoSiaKpNOleJpZRgHiZDSinyryPdT/O2ubu/FJFX,iv:JE+cYV4pc7gha5ZthHJdaaILll97eQcqeKzWlZ+vM44=,tag:flA0QMIRrqrbM2oGZ5CVrg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOXdEWm16NWhBVE95SXlj
        ZUV3eVF0d29QOUtXN01xMENnUHlIUUpOSkJvCjF1VlRYeThnS1EwdDBnMEgxSVZz
        U1BPVkdiY3dyZUg4Vm5UM0k0U1MxU1kKLS0tIFphWlJZaGtTOHJUd1V2cXFVRC81
        V0tsOTdLUnZ5Y0tFN2tBczVzS1FPYjQKuEzH4lh76kG8XI3sQ/YDsW7xzEJsfHZw
        OTD4wR0YsECjsCduLwrsSuH1RQoIBQtYg7Dhoxs9zSoRdd3VqhE/Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T14:35:40Z"
  mac: ENC[AES256_GCM,data:OcYNjk9GZDORDcycvgSij5H5h1HMhYmtQca9dqULEhjjCx5v4pkICmLt+9HzTjolNCUVVI5OrO3EDkg3KDNDzAnvwzp653UCyZfKoSAwbhWisAVd9mQTH/btS903DCTg/Vi1xkaNlf8u8Z9v+oqnJEMFHr2JeoTtr0mGUROVTew=,iv:Akoi45KyLFyBuji0pwcu+2zj/SrNsMATmKJAk4fVL/g=,tag:u1aszP4f1sH2R4otDdKJiA==,type:str]
  version: 3.13.0
