apiVersion: v1
kind: Secret
metadata:
  name: navidrome-scrobbler
  namespace: media
type: Opaque
stringData:
  ND_LASTFM_APIKEY: ENC[AES256_GCM,data:+gEXuo7po2wdm8WdTqgpuwaZOy5gNtzM3DpUg9f6ESE=,iv:ZCrJNWjDsgYh1867MYy3JEQoM/VLfXEE2Ylzr+2Cet8=,tag:+kAjnrH1OdsFEWkBQJURPA==,type:str]
  ND_LASTFM_SECRET: ENC[AES256_GCM,data:Xu8YEsJn/J6gyOM0b/AZbTW7Y3SKd3Ne0Bc7PAN1xi0=,iv:+9u2MxaEpIX6BcS27oy7+hQle091IUkfqfUZZMQ5eTA=,tag:Ubvq1yVQogaWm4Mh+eQlwA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVlFCa2ppZm1QNmVlT1JE
        S2NuZTRINkRCRTlNQmQ1V3d0SGF0N1BLcVUwCnpvUkNuSHFvcUI0YnV3VjNLTFFs
        Z1QzU2syekw4cU5TSi9OZHhOS0k0MVkKLS0tIDM4Q3YwOXZKZEpucy9WdmJuanI4
        U05tNktobkprS1pGRVQxRDhLOVRUM2MKQxCjuRc5Yjcpc26xQfp5HSSeMVKsz4xf
        XHQ5m8k1yIARKTc1e9ojJLXoOg+h2wOeQs2jITh3UmV3OxtiWAWAVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T16:43:12Z"
  mac: ENC[AES256_GCM,data:18Gyk29nYIjgcEVxXpYV50PFVREMiMjlUzVxvb4Ai6+Unro8pEJ6aKp+eiIfl3iut3Wo5TaUDB1lVXrM+qE88auBAN2Ieib4ne1luIaRTpYuf4ju9C+GxOaUu3nbT8WeFEMg8bHUbIfCoAYCaG6RjZTrmO6jGzj/wq/hXEnWHr8=,iv:uAsP0OZjHuUmC6PgA4xk6/jH+3VWsJD/sBsXn+FvVjU=,tag:VAuHNNreUYo6cVEcH+v10A==,type:str]
  version: 3.13.3
