apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: local-network-connector
  namespace: tailscale
spec:
  hostname: homelab-subnet-router
  subnetRouter:
    advertiseRoutes:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
  exitNode: true
  tags:
    - tag:k8s-subnet-router
