apiVersion: v1
kind: Secret
metadata:
  name: pocketid-encryption-key
  namespace: default
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:3ccsz4emK2FNDjNTHF5IoOII2PtwZJoI0Sw5buQF217kBUF1r83qkb21CpM=,iv:s8mZf9n1wDr3qbBT5aAv6BM63Qf+pIlByBXnIE44vtE=,tag:64ZAgpgkfmuLsXurNzaVQg==,type:str]
sops:
  age:
    - recipient: age1gzp39gyv25y689qnwl74tuj5qls2g4zgu3rllf83syu9eveje37s3gdlq2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZzc4YmplNC82VDExNEVm
        eElzS3B2TDBaN0Z4cTFmVncrcS9BQ2xvZFRRCndLNmNCZk9hdnljN0dVYy9pMUhm
        dTVNWVo3alFDQjh6aE1NWUF3dXJZWGcKLS0tIE9jMDJ1Y2piVW9QcVo3bG5YeDcy
        V1RvYVlNdEtzUDJPSTVLdjlYaDhTQ0EKehqWP1TnFhr3E5cOe9mmULj5kNV3Y0A8
        kQbiezs3gKp+eX2+WPYGty3jUALflimNvBnuP98w/u5JgsMBK87gLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T16:27:32Z"
  mac: ENC[AES256_GCM,data:yHSodrZ/394bxK5HLzukyay7Ql2naKHmPzpydeX0qBfoXL3c7cRiX8oynZrQR9fudidM3C5z3LQkc3bpfWpjPjC7kELkec90k7eL+uE0qPIsnGE5rcpdqXe6+lbXIBtnwHw4Ul2gq7xcWEKp748votCSArybA/9AaYE3xoDp2V4=,iv:1hNf4g+5G60LbR8wOgrm+pzJdcmR2GzfSgzeAtpzgmg=,tag:Lf9Tb/170ibF5j5mwbRxQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
