apiVersion: v1
kind: Secret
metadata:
  name: pocketid-encryption-key
  namespace: default
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:E+W4ISp4vnKHJrPnQiIfTZCZ1Czks9NgG9nGDIAsNdbX99nbbieMFjbUbJ8=,iv:2+On06+zVXUwEMT6Mem2kGD+Jw7R22imibpIBklVxJA=,tag:wskC21YjyUrxx46Ye5qy8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU3dxTGsrTWxhT3o3a3dv
        RytBN1hyUXN4VWwvSmxBM1pId1Y0aklHb1FZCjgxREZCaFNGYXlQNkErcTFDOGN5
        UFRoRjVNN3E5N1JMNTNzT1d1VENTeUEKLS0tIEhuVW5IRVFvemgrWG1SRk5PcXFS
        eStxVzZmNEQ4aXJ4TkRQSHY0aVk2SFUKeG0TD0R0+XqTvBfG9tzsT+4KxXiF+MTX
        bm2eIOb6jRiW3toUI7hBYJIqCwvhTQQANfO8mfyfchxQeiSyThmo1A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qjhqpf8v4u3exgumunm5ujnrf6cehqls7vceuk9w8ylgl3cpusyspvr6vm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T12:21:08Z"
  mac: ENC[AES256_GCM,data:BkRx/uPVdEE5wmN5yYZA2IBfUN2df0vpSvkl+US6C9WZIYJPCpMfUUPnGT08JqwNZO5/nHbzpgRaDW9GN7usl8WiiJUi2k+7fkzw4uZcIfc+4HDuJlzrp7SGQe9qULd5DT/Fnr6R9mFgsoy1+EepvDmkYzndLgern/QogDS7uPY=,iv:xZIx5IFhan//c12sOuz0/741zVyyDB9G2yKz4xrd9EY=,tag:rFSGPLB3cCg+/xw0hbUWBQ==,type:str]
  version: 3.13.0
